name: Orchestrator call
on:
    workflow_dispatch:
permissions:
  contents: read         
  security-events: write
  actions: read
  packages: write
jobs:
    orchestrator:
        uses: gha-sec-scans/orchestrator/.github/workflows/main.yaml@feature/defectdojo
        with:
            app-port: '8080'
            app-path: '/WebGoat'
            defectdojo_product_id: '1'
        secrets: inherit
        