name: Orchestrator call
on:
    workflow_dispatch:
permissions:
  contents: read         
  security-events: write
  actions: read
  packages: write
jobs:
    orchestrator:
        uses: gha-sec-scans/orchestrator/.github/workflows/main.yaml@feature/predeploy
        with:
            app-port: '8080'
        secrets: inherit